### ISSUE TITLE
implement different preconditioning methods

### ISSUE THREAD

**Issue by lucaferranti** [lucaferranti/IntervalLinearAlgebra.jl#12]
For example, sometimes preconditioning by `Diagonal(Ac)^-1` gives better results than `Ac^-1`. It might be good to offer different preconditioning mechanisms. 

I don't know whether there are some criteria or heuristic techniques to choose the preconditioning method for a given system.

**Comment by mforets** [comment]
> I don't know whether there are some criteria or heuristic techniques to choose the preconditioning method for a given system.

Section 5.43 in Horacek's thesis, and also the references in the final paragraph of that section, seem relevant.

**Comment by lucaferranti** [comment]
For start, simply allow the user to choose what preconditioning of the 3 following

- None
- inv(mid(A))
- inv(diag(mid(A))

the type of preconditioning could be an extra field of the solver, e.g.
```
struct GaussSeidel
max_iterations::Int
atol::Float64
precondition::Function
end

gs = GaussSeidel(20, 0.0, inv_mid) # inv_mid name of function
```
 and then inside `solve`

```
solve(A, b, method)
A, b = method.precondition(A, b)
....
```

DL for PR: 24.06.2021

**Comment by mforets** [comment]
Feel free to ignore this suggestion at an early stage, but consider using [value types](https://docs.julialang.org/en/v1/manual/types/#%22Value-types%22) here, with the advantage that the method (in this case, preconditioning) can be quite easily generalized to normal functions (but can still behave as such, see example below).

Structs can hold other useful information, such as, say a cache: imagine that you want to solve repeatedly `Ax = b` for the same `A` but different `b`s, then preconditioning `A` can be done only once.

Here is an example (I didn't actually try it, it is a sketch):

```julia
struct GaussSeidel{PT}
    max_iterations::Int
    atol::Float64
    precondition::PT
end


abstract type AbstractPrecondition end

function precondition(A::AbstractMatrix, alg::AbstractPrecondition=InvPrecondition(A))
    if is_precondition_computed(alg)
        Q = _precondition(alg) # return cached value
    else
        Q = _precondition(alg(A)) # compute and return new value
    end
    return Q
end

# this is a "no-op"
struct NoPrecondition{T} <: AbstractPrecondition
    A::T
end
_precondition(alg::NoPrecondition) = alg.A
is_precondition_computed(::NoPrecondition) = true

mutable struct InvPrecondition{T, S} <: AbstractPrecondition
    A::T
    Q::S
end
InvPrecondition(A::AbstractMatrix) = InvPrecondition(A, inv(mid(A)))
_precondition(::InvPrecondition) = prec.Q
is_precondition_computed(alg::InvPrecondition) = !ismissing(alg.Q)

mutable struct InvDiagPrecondition{T, S} <: AbstractPrecondition
    A::T
    Q::S
end
InvDiagPrecondition(A::AbstractMatrix) = InvPrecondition(A, inv(diag(mid(A))))
_precondition(::InvDiagPrecondition) = prec.Q
is_precondition_computed(alg::InvDiagPrecondition) = !ismissing(alg.Q)

```

**Comment by dpsanders** [comment]
I was also going to suggest this. (But I don't think these are value types; this is type-based dispatch.)

**Comment by dpsanders** [comment]
For now I would not try to cache the preconditioning (if I understand correctly that that's what you're suggesting, Marcelo).

**Comment by lucaferranti** [comment]
I also considered about using types, I was thinking about a similar structure of how I implemented the solvers, i.e.

```julia
abstract type Precondition end

struct InvMidPrecondition end

function (invMid::InvMidPrecondition)(A, b)
  Acinv = inv(mid.(A))
  return Acinv*A, Acinv*b
end

struct InvDiagPrecondition end

function (invDiag::InvDiagPrecondition)(A, b)
  Acinv = inv(Diagonal(mid.(A)))
  return Acinv*A, Acinv*b
end

struct NoPrecondition end

(np::NoPrecondition)(A, b) = A, b
```

then could be e.g.
```julia
struct GaussSeidel{PT}
   max_iterations::Int
   atol::Float64
   precondition::PT
end

function solve(A, b, method)
   A, b = method.precondition(A, b)
   .....
```

**Comment by dpsanders** [comment]
Maybe the preconditioner should be separate from the solver type?

**Comment by lucaferranti** [comment]
do you mean not having precondition as field of the solver and then having

```julia
solve(A, b, method, pt::Precondition)

  A, b = pt(A, b)
  ....
````

**Comment by dpsanders** [comment]
Yes that's what I meant. I'm not sure if that's a good idea or not.

**Comment by lucaferranti** [comment]
At least easier to implement to start, it also allows to try different preconditioning without having to recreate the solver. Also, as far as I understand, the preferable preconditioning algorithm depends (heuristically) more on the matrix type, not on the solver that one wants to use.

**Comment by mforets** [comment]
Update, based on 29th june meet:

```julia
# fallback
function _default_precondition(A, method::AbstractSolver)
    # ....
end

# specific default preconditioning methods
function _default_precondition(A, method::GaussElimination)
    if is_sdd_matrix || is_M_matrix 
        return NoPrecondition()
    else
        return InverseMidpoint()(A, b)
    end
end

function _default_solver()
    GaussEliminiation()
end

function solve(A, b,
               solver::AbstractSolver=_default_solver(),
               precondition::AbstractPrecondition=_default_precondition(A, method))
   
    # precondition
    Ap, bp = precondition(A, b)

    # compute solution
    return solver(Ap, bp)
end
```
