### ISSUE TITLE
docs didn't deploy

### ISSUE THREAD

**Issue by lucaferranti** [lucaferranti/IntervalLinearAlgebra.jl#34]
I setup the deploy key and secret key called `DOCUMENTER_KEY` but doesn't work. I'll try to go through the instructions again and see if I missed something.

**Comment by lucaferranti** [comment]
the gh_pages branch hasn't been created either

**Comment by lucaferranti** [comment]
do I need to also create the `GITHUB_TOKEN` or does that exist by default?

**Comment by mforets** [comment]
don't know if this answers your question, but i usually have to create a documenter deploy key (under https://github.com/path-to-repo/settings/keys) *and* also a repository secret DOCUMENTER_KEY (under https://github.com/..../settings/secrets/actions ). i get those from DocumenterTools as explained in the manual

**Comment by lucaferranti** [comment]
yep I think I created those: https://github.com/lucaferranti/IntervalLinearAlgebra.jl/settings/keys and https://github.com/lucaferranti/IntervalLinearAlgebra.jl/settings/secrets/actions I'll try to delete those and recreate

**Comment by lucaferranti** [comment]
```
┌ Info: Deployment criteria for deploying devbranch build from GitHub Actions:
│ - ✔ ENV["GITHUB_REPOSITORY"]="lucaferranti/IntervalLinearAlgebra.jl" occurs in repo="github.com/lucaferranti/IntervalLinearAlgebra.jl"
│ - ✔ ENV["GITHUB_EVENT_NAME"]="push" is "push"
│ - ✘ ENV["GITHUB_REF"] matches devbranch="master"
│ - ✔ ENV["GITHUB_ACTOR"] exists and is non-empty
│ - ✔ ENV["DOCUMENTER_KEY"] exists and is non-empty
└ Deploying: ✘
┌ Warning: Possible deploydocs() misconfiguration: main vs master
│ Documenter's configured primary development branch (`devbranch`) is "master", but the
│ current branch (from $GITHUB_REF) is "main". This can happen because Documenter uses
│ GitHub's old default primary branch name as the default value for `devbranch`.
│ 
│ If your primary development branch is 'main', you must explicitly pass `devbranch = "main"`
│ to deploydocs.
```

I think this is the relevant issue, I'll try to give `devbranch="main"` to deploydocs in the `make.jl`

**Comment by lucaferranti** [comment]
yep that worked, closing.
