### ISSUE TITLE
solvers types names

### ISSUE THREAD

**Issue by lucaferranti** [lucaferranti/IntervalLinearAlgebra.jl#45]
The current type system for the solvers (including the changes in the latest PRs)

* LinearSolver
  - DirectSolver
    + GaussElimination
    + HansenBliekRohn
    + LinearOettliPrager
  - IterativeSolver
    + GaussSeidel
    + Jacobi
    + Krawczyk
  - OettliPrager (solves nonlinear equalities using ICP.jl)
  
  I think there's room for improvement, here's a proposal
  
* AbstractIntervalLinearSolver
  - AbstractDirectIntervalLinearSolver
    + GaussElimination
    + HansenBliekRohn
    + LinearOettliPrager
  - AbstractIterativeIntervalLinearSolver
    + GaussSeidel
    + Jacobi
    + LinearKrawczyk (to distinguish from `Krawczyk` exported in IntervalRootFining.jl)
    + NonLinearOettliPrager
    
  what do you think? Feel free to comment other proposals or suggestions

**Comment by lucaferranti** [comment]
similarly for Preconditioning the current `Precondition` could be renamed `AbstractPrecondition`

**Comment by lucaferranti** [comment]
I have mixed feelings about the verbose abstract names, on the one hand the package is called `IntervalLinearAlgebra` so maybe the `IntervalLinear` is redundant, but on the other hand they are exact and unambiguous, Otherwise `DirectSolver` could be expected to solve also non-interval non-linear problems.

**Comment by lucaferranti** [comment]
Gauss -> Gaussian

**Comment by mforets** [comment]
the advantage of haivng `Abstract...` is that it's clear they are abstract types. at least for someone new to the library.

i would only suggest to remove the "Interval" word for the direct subtypes of `AbstractIntervalSolver`, like this:

* AbstractIntervalSolver

  - AbstractDirectSolver
    + GaussElimination
    + HansenBliekRohn
    + LinearOettliPrager

  - AbstractIterativeSolver
    + GaussSeidel
    + Jacobi
    + LinearKrawczyk (to distinguish from `Krawczyk` exported in IntervalRootFining.jl)
    + NonLinearOettliPrager

**Comment by lucaferranti** [comment]
just double checking, the most abstract would be `AbstractSolver` `?

**Comment by mforets** [comment]
the abstract types are generally not exported from the library. hence you could pick the name you prefer, since eg. `AbstractSolver`  (which exists in other libraries for sure), is going to be used only internally.
