### ISSUE TITLE
Setup Docs / Quickstart guide

### ISSUE THREAD

**Issue by mforets** [lucaferranti/IntervalLinearAlgebra.jl#6]
* related reading: https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006561

**Comment by lucaferranti** [comment]
To concretize:

- [ ] add a REFERENCES.md file to the repo containing a list of references, the docstrings can then have a link to the corresponding reference
- [ ] add examples, tutorials. These should go to the [juliaintervals page](https://juliaintervals.github.io) at some point, probably after the repo has been moved to the organisation?

**Comment by lucaferranti** [comment]
fixed in #27
