### ISSUE TITLE
Difference between static / regular arrays

### ISSUE THREAD

**Issue by mforets** [lucaferranti/IntervalLinearAlgebra.jl#9]
```julia
julia> A = @SMatrix [2..4 -2..1; -1..2 2..4]
julia> b = @SVector [-2..2, -2..2];

julia> Am = Matrix(A)
julia> bm = Vector(b);

julia> solve(A, b, Jacobi())
solve(A, b, Jacobi()) = Interval{Float64}[[-14.0001, 14.0001], [-14.0001, 14.0001]]

julia> solve(Am, bm, Jacobi())
solve(Am, bm, Jacobi()) = Interval{Float64}[[-45.7501, 45.7501], [-45.0795, 45.0795]]
```

**Comment by lucaferranti** [comment]
To recap (and as a note to myself), the result with static matrix is the "correct one" (in the sense, it is what is reported in the reference thesis). The different behaviour arises from the backslash using in `precondition`, which has a different implementation for static and normal arrays. Replacing `Ac\A` and `Ac\b` to `inv(Ac)*A` and `inv(Ac)*b`, fixes the problem.

```
julia> x1 = solve(A, b, jac)
2-element MVector{2, Interval{Float64}} with indices SOneTo(2):
 [-14.0001, 14.0001]
 [-14.0001, 14.0001]

julia> x2 = solve(Am, bm, jac)
2-element Vector{Interval{Float64}}:
 [-14.0001, 14.0001]
 [-14.0001, 14.0001]
```

**Comment by lucaferranti** [comment]
probably the current `precondition` function should use the epsilon-inflation method though (section 5.5 of Horácek thesis)
